# .bash_profile

export EDITOR=nvim
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Get the aliases and functions
[ -f $HOME/.bashrc ] && . $HOME/.bashrc

[ -f $HOME/.cargo/env ] && . $HOME/.cargo/env

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH=$PATH:/home/yui/.dvm/sym
export PATH=$PATH:/home/yui/.kotlin-native/linux/bin
export PATH=$PATH:/home/yui/.deno/bin
export PATH=$PATH:/home/yui/.yarn/bin
export PATH=$PATH:/home/yui/.dotnet/tools # Add .NET Core SDK tools
