# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
    . ~/.bashrc
fi

export EDITOR=nvim

export JAVA_VERSION=17
export DOTNET_CLI_TELEMETRY_OPTOUT=1

export PATH=$PATH:$HOME/.local/bin

